management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "health,prometheus"

spring:
  data:
    mongodb:
      user: ${DATABASE_USERNAME:test}
      password: ${DATABASE_PASSWORD:test}
      uri: mongodb://${DATABASE_HOST:localhost}:${DATABASE_PORT:27017}/${DATABASE_DBNAME:db}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      connectTimeout: 100
      timeout: 100
  kafka:
    consumer:
      auto-offset-reset: latest
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
      group-id: consumer_${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*" # change this with your event packages
    producer:
      acks: -1
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

topics:
  order:
    events:
      name: order-events
  inventory:
    events:
      name: inventory-events
  payment:
    events:
      name: payment-events
  notification:
    events:
      name: notification-events