services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'

  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    environment:
      - 'ZOOKEEPER_CLIENT_PORT=2181'
      - 'ZOOKEEPER_TICK_TIME=2000'
    ports:
      - '22181:2181'

  kafka:
    image: 'wurstmeister/kafka:latest'
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
      - '59092:59092'
    environment:
      - 'KAFKA_BROKER_ID=1'
      - 'KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181'
      - 'KAFKA_LISTENERS=PLAINTEXT://kafka:59092,PLAINTEXT_HOST://kafka:9092'
      - 'KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:59092,PLAINTEXT_HOST://localhost:9092'
      - 'KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      - 'KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT'
      - 'KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1'
      - 'KAFKA_CREATE_TOPICS=order-events:1:1,inventory-events:1:1,payment-events:1:1,notification-events:1:1'